DEF MAX_PLAYER_NAME_CHARS       EQU 6
DEF MAX_PLAYER_NAME_LENGTH      EQU MAX_PLAYER_NAME_CHARS * 2

RSRESET
DEF NAME_BUFFER_NAME     RB MAX_PLAYER_NAME_LENGTH ; $0
DEF NAME_BUFFER_NAME_END RB ; $c
DEF NAME_BUFFER_GENDER   RB ; $d
DEF NAME_BUFFER_ID       RW ; $e

DEF NAME_BUFFER_LENGTH EQU _RS ; 16

DEF MAX_DECK_NAME_LENGTH        EQU 20 * 1 ; note that its unit is byte!

DEF NAMING_SCREEN_BUFFER_LENGTH EQU 24

DEF MAX_MULTILINE_INPUT_CHARS_PER_LINE   EQU 18
DEF MAX_MULTILINE_INPUT_LENGTH_PER_LINE  EQU MAX_MULTILINE_INPUT_CHARS_PER_LINE * 2                          ; 36
DEF MAX_MULTILINE_INPUT_LINES            EQU 2
DEF MAX_MULTILINE_INPUT_CHARS            EQU MAX_MULTILINE_INPUT_CHARS_PER_LINE * MAX_MULTILINE_INPUT_LINES  ; 36
DEF MAX_MULTILINE_INPUT_LENGTH           EQU MAX_MULTILINE_INPUT_LENGTH_PER_LINE * MAX_MULTILINE_INPUT_LINES ; 72

DEF PER_LINE_INPUT_SCREEN_BUFFER_LENGTH  EQU MAX_MULTILINE_INPUT_LENGTH_PER_LINE + 2                         ; 38
DEF MULTILINE_INPUT_SCREEN_BUFFER_LENGTH EQU MAX_MULTILINE_INPUT_LENGTH + 2                                  ; 74

	const_def
	const NAME_MODE_HIRAGANA  ; $0
	const NAME_MODE_KATAKANA  ; $1
	const NAME_MODE_UPPER_WIDE ; $2
	const NAME_MODE_UPPER_HALF ; $3
DEF NUM_NAME_MODES EQU const_value

; keyboard commands:
	const_def $01
	const KEYBOARD_DONE     ; $01
	const KEYBOARD_UNKNOWN  ; $02
