INCLUDE "macros.asm"
INCLUDE "constants.asm"

INCLUDE "text/text_offsets.asm"

INCLUDE "text/text1.asm"
INCLUDE "text/text2.asm"
INCLUDE "text/text3.asm"
INCLUDE "text/text4.asm"
INCLUDE "text/text5.asm"
INCLUDE "text/text6.asm"
INCLUDE "text/text7.asm"
INCLUDE "text/text8.asm"
INCLUDE "text/text9.asm"
INCLUDE "text/text10.asm"
INCLUDE "text/text11.asm"
INCLUDE "text/text12.asm"
INCLUDE "text/text13.asm"
INCLUDE "text/text14.asm"
INCLUDE "text/text15.asm"
INCLUDE "text/text16.asm"
INCLUDE "text/text17.asm"
